### ISSUE TITLE
Am I using this correctly?

### ISSUE THREAD

**Issue by rlboyce** [sls1j/caveSpy#2]
I know very little about this sort of thing, so there's a good chance I'm doing something wrong. I've tried to vary the parameters, even though they are supposed to be optional. Is it possible that the .las file I'm using is not compatible with this program? I've attached a screenshot of my last few failed attempts. Thanks!

![capture](https://user-images.githubusercontent.com/36142623/35785466-94e2e70a-09ee-11e8-92ef-e36de486f106.PNG)

**Comment by sls1j** [comment]
The second one iteration looks right and should have produced input.  I
wonder if there's something slightly different with the .las file which has
exposed a bug in the software.  "Object reference not set...." error means
something isn't right internal to the program.  Where did you get the .las
file from?  I could download it so I could reproduce the issue and fix it.

Thanks,

Brian

**Comment by rlboyce** [comment]
Hi Brian,

I downloaded the file from the Pennsylvania Spatial Data Access Imagery Navigator. It is the 22001920PAS tile. I've included a link to it below, but I'm not sure it will work.

[ftp://ftp.pasda.psu.edu/pub/pasda/pamap/pamap_lidar/cycle1/LAS/South/2007/20000000/22001920PAS.zip](url)

Thanks for the help!

**Comment by sls1j** [comment]
Thanks!  I've got it and will try to take a look at it today and see what I can do to get it working.

**Comment by sls1j** [comment]
Well I found the problem with my code.  The issue is not handling different
forms Projection data from the las file well.  It has it in the header
different than the sources I modeled the code with.  I'll be working on a
way to fix it.  I'm in the middle of some big rework.  It might be a couple
of days before I can get a fix in :( but it might be today too.

Brian

**Comment by rlboyce** [comment]
I'm not in a rush, so a few days is no biggie. I am mostly just curious to see what the output is like, how capable the software is, and if it could save me any time. I use lidar hillshades all the time to find sinks, so a program like this is of great interest to me. Good luck, and thanks for sharing it with everyone.

**Comment by sls1j** [comment]
Well I finished the updates that includes a fix and workaround for the UTM zone problem.  This update quite a bit more than just your bug.  The command line options parameters have changed some.  For your use the following command line should work:
```
CaveSpy.exe --script default.lisp --input c:\maps\22001920PAS.las --image-size 3000 --output c:\maps\22001920PAS.kml --default-zone 17T
```
I'm assuming your UTM zone is 17T it could be 17S, 18S, or 18T

You can find a rough map of the zones here: http://www.dmap.co.uk/utmworld.htm

Let me know how it works or doesn't work.

**Comment by rlboyce** [comment]
Thanks for fixing this. I should have some time tomorrow evening to try it out. I'll let you know if the issue is resolved on my end.

**Comment by rlboyce** [comment]
The program successfully generated an image on my computer!

The location, scale, and rotation of the image seems to be off, but now I at least have an idea of what the output of the program is.

Thanks again for helping me, and I look forward to seeing the evolution of the program.
