### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by tokrv** [sls1j/caveSpy#3]
HI,

I tried to find another way to contact the developer but to no avail. I was wondering if is this project still open since the exe files linked in the description point all to an unregistered domain. I tried to download the source code and compile it with VS 2019 on Win7 but I'm having issues due to the fact that I'm quite ignorant in coding in a Windows environment.
Any help or suggestions?
Thank you in advance,

Tom

**Comment by sls1j** [comment]
It is semi active.  Been extra busy with work and haven't got back to it in
a while.  I'm out to church right now but will try to get the binaries up
today.

Brian

**Comment by tokrv** [comment]
Actually I managed to compile and run the program. Now I need to understand how to use it with the LAS data I have. 
Thank you very much, I close the report since there isn't any actual issue. :)

Tom
